id: fedefed3-94bb-42bb-8486-ca3f08ed5b44
version: 13
vcShouldKeepItemLegacyProdMachine: false
name: Nutanix-test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 820c9c94-2bf4-4e77-8cfe-96d0d17e5ef1
    type: start
    task:
      id: 820c9c94-2bf4-4e77-8cfe-96d0d17e5ef1
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: d685992f-8fc3-49bd-811a-bc62040cc9c7
    type: regular
    task:
      id: d685992f-8fc3-49bd-811a-bc62040cc9c7
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 742dbce9-0d17-4d3b-86ee-04e27ddad58f
    type: regular
    task:
      id: 742dbce9-0d17-4d3b-86ee-04e27ddad58f
      version: -1
      name: Nutanix Get hosts
      description: Get the list of physical hosts configured in the cluster.
      script: '|||nutanix-hypervisor-hosts-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      filter: {}
      limit: {}
      page: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 2f725f02-a03b-49b3-80c2-457d41d91173
    type: regular
    task:
      id: 2f725f02-a03b-49b3-80c2-457d41d91173
      version: -1
      name: Nutanix Get VMs
      description: Get a list of virtual machines.
      script: '|||nutanix-hypervisor-vms-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      filter: {}
      length: {}
      offset: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: fd1f8160-860f-4aa7-823e-2b47ca2948d3
    type: condition
    task:
      id: fd1f8160-860f-4aa7-823e-2b47ca2948d3
      version: -1
      name: Is Virtual Machines List Empty?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEmpty
          left:
            value:
              simple: NutanixHypervisor.VM
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: cdcf461f-d524-4231-8019-20dcba98bb08
    type: regular
    task:
      id: cdcf461f-d524-4231-8019-20dcba98bb08
      version: -1
      name: Nutanix Get Alerts
      description: Get the list of Alerts generated in the cluster which matches the
        filters if given.
      script: '|||nutanix-alerts-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      acknowledged: {}
      alert_type_uuids: {}
      auto_resolved: {}
      classifications: {}
      end_time: {}
      entity_ids: {}
      entity_types: {}
      impact_types: {}
      limit: {}
      page: {}
      resolved: {}
      severity: {}
      start_time: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: e31ef5c0-4f44-4ce7-80ec-9d8d35e16bac
    type: regular
    task:
      id: e31ef5c0-4f44-4ce7-80ec-9d8d35e16bac
      version: -1
      name: 'Nutanix Change Power State '
      description: Set power state of a virtual machine.  If the virtual machine is
        being powered on and no host is specified, the scheduler will pick the one
        with the most available CPU and memory that can support the Virtual Machine.
        Note that no such host may not be available. If the virtual machine is being
        power cycled, a different host can be specified to start it on. This is also
        an asynchronous operation that results in the creation of a task object. The
        UUID of this task object is returned as the response of this operation. This
        task can be monitored by using the nutanix-hypervisor-task-poll command.
      script: '|||nutanix-hypervisor-vm-powerstatus-change'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      host_uuid: {}
      transition:
        simple: POWERCYCLE
      uuid:
        complex:
          root: NutanixHypervisor.VM
          accessor: uuid
          transformers:
          - operator: FirstArrayElement
      vm_uuid:
        complex:
          root: NutanixHypervisor.VM
          accessor: uuid
          transformers:
          - operator: FirstArrayElement
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: aa08d897-a4fa-4bd1-8366-6f3ec1dfb1af
    type: regular
    task:
      id: aa08d897-a4fa-4bd1-8366-6f3ec1dfb1af
      version: -1
      name: Nutanix Task Poll For Power State
      description: Poll tasks given by task_ids to check if they are ready. Returns
        all the tasks from 'task_ids' list that are ready at the moment Nutanix service
        was polled. In case no task is ready, waits until at least one task is ready,
        unless given argument 'timeout_interval' which waits time_interval seconds
        and in case no task had finished, returns a time out response.
      script: '|||nutanix-hypervisor-task-poll'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      task_ids:
        simple: ${NutanixHypervisor.VMPowerStatus.task_uuid}
      timeout_interval: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 6bc3f53c-89dd-43b5-8663-5a62437ada5b
    type: condition
    task:
      id: 6bc3f53c-89dd-43b5-8663-5a62437ada5b
      version: -1
      name: Is Alert List Empty?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEmpty
          left:
            value:
              simple: NutanixHypervisor.Alerts
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 0b62b122-719f-4a6f-8c3f-8d9c1fdc63fe
    type: regular
    task:
      id: 0b62b122-719f-4a6f-8c3f-8d9c1fdc63fe
      version: -1
      name: Nutanix Acknowledge Alert
      description: Acknowledge alert with the specified alert_id.
      script: '|||nutanix-alert-acknowledge'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      alert_id:
        simple: WAIT_FOR_CONTEXT_PATH_FROM_ARSENY
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: b795829f-cac4-4fbd-8d97-4a9a35f7214f
    type: regular
    task:
      id: b795829f-cac4-4fbd-8d97-4a9a35f7214f
      version: -1
      name: Nutanix Resolve Alert
      description: Resolve alert with the specified alert_id.
      script: '|||nutanix-alert-resolve'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      alert_id:
        simple: WAIT_FOR_CONTEXT_PATH_FROM_ARSENY
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: 12505de5-ad70-4d72-89c7-7a3bab17b3cf
    type: regular
    task:
      id: 12505de5-ad70-4d72-89c7-7a3bab17b3cf
      version: -1
      name: Nutanix Acknowledge Alerts By Filters
      description: Acknowledge alerts using a filters.
      script: '|||nutanix-alerts-acknowledge-by-filter'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      classifications: {}
      end_time: {}
      entity_type_ids: {}
      entity_types: {}
      impact_types: {}
      limit: {}
      severity: {}
      start_time: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: 5fbbc105-8fcf-4b90-8211-204bb5c8de82
    type: regular
    task:
      id: 5fbbc105-8fcf-4b90-8211-204bb5c8de82
      version: -1
      name: Nutanix Resolve Alerts By Filters
      description: Resolve alerts using a filters.
      script: '|||nutanix-alerts-resolve-by-filter'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      classifications: {}
      end_time: {}
      entity_type_ids: {}
      entity_types: {}
      impact_types: {}
      limit: {}
      severity: {}
      start_time: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: b8fde65e-7746-48cc-88f0-68c8a4601553
    type: regular
    task:
      id: b8fde65e-7746-48cc-88f0-68c8a4601553
      version: -1
      name: Playbook Done
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2340,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0