id: Set OOO users to layout
version: -1
name: Set OOO users to layout
description: "This playbook is used to display the out of the office users in the\
  \ layout.\nThe out of the office users will be taken from OOO list. \nThe list located\
  \ in:\nSettings -> advanced -> lists"
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 5a52a1fd-4859-4baf-813c-a6d85544d0cc
    type: start
    task:
      id: 5a52a1fd-4859-4baf-813c-a6d85544d0cc
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 71634071-a342-4a54-88bb-e195be6e40bd
    type: regular
    task:
      id: 71634071-a342-4a54-88bb-e195be6e40bd
      version: -1
      name: Get list of OOO users
      description: commands.local.cmd.list.get
      script: Builtin|||getList
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      listName:
        simple: OOO List
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 270
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 87d8ca30-5236-4bfe-8ba4-fbe644d43bb6
    type: regular
    task:
      id: 87d8ca30-5236-4bfe-8ba4-fbe644d43bb6
      version: -1
      name: Set OOO users to layout
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      append: {}
      key:
        simple: OOOusers
      stringify: {}
      value:
        complex:
          root: inputs.OOO list
          transformers:
          - operator: ParseJSON
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 4be262b5-7d57-4af5-812a-dbd3d5de476e
    type: title
    task:
      id: 4be262b5-7d57-4af5-812a-dbd3d5de476e
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 860
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: b198034e-c62c-4048-8f1f-ba10263df679
    type: regular
    task:
      id: b198034e-c62c-4048-8f1f-ba10263df679
      version: -1
      name: Set grid OOO users to layout
      description: Creates a Grid table from items or key-value pairs.
      scriptName: SetGridField
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      columns:
        simple: User name,Off until, Added by
      context_path:
        simple: OOOusers
      grid_id:
        simple: outofftheoffice
      keys:
        simple: user,offuntil,addedby
      overwrite: {}
      sort_by: {}
      unpack_nested_elements: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 650
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 805,
        "width": 380,
        "x": 450,
        "y": 120
      }
    }
  }
inputs:
- key: OOO list
  value:
    complex:
      root: lists
      accessor: OOO List
  required: false
  description: The out of office list.
  playbookInputQuery:
outputs: []
tests:
- No tests (auto formatted)
fromversion: 6.0.0
